#!/bin/sh
set -e

. /usr/share/debconf/confmodule

case "$1" in
    purge)
        ucf --purge /etc/opt/slapos/slapos.cfg

        rm -rf /var/opt/slapos/ /srv/slapgrid/ /opt/slapgrid/ \
		/etc/opt/slapos/ /opt/slapos/
	;;
esac

#DEBHELPER#

exit 0
