#!/bin/sh
sleep 15
SLAPOS_CONFIGURATION='%(slapos_configuration)s'
i=0
false
while [[ $? != 0 ]]; do
    sleep $(($i*60))
    if [[ $i < 20 ]]; then
        let i++
    fi
    echo "Retrying slapformat"
    /opt/slapos/bin/slapformat --verbose --console $SLAPOS_CONFIGURATION/slapos.cfg
done